//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.ORM.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;

	#region User
	public partial class User : BaseEntity
	{
		/// <summary>
		/// Get or set Id
		/// </summary>
		public Int32 Id { get; set; }

		/// <summary>
		/// Get or set UserName
		/// </summary>
		public String UserName { get; set; }

		/// <summary>
		/// Get or set Email
		/// </summary>
		public String Email { get; set; }

		/// <summary>
		/// Get or set FirstName
		/// </summary>
		public String FirstName { get; set; }

		/// <summary>
		/// Get or set LastName
		/// </summary>
		public String LastName { get; set; }

		/// <summary>
		/// Get or set BirthDate
		/// </summary>
		public Nullable<DateTime> BirthDate { get; set; }

		/// <summary>
		/// Get or set Roles
		/// </summary>
		public List<Role> Roles { get; set; }

		public User()
		{
			Roles = new List<Role>();
		}
	}

	public partial class UserRepository : BaseRepository
	{
	}
	#endregion

	#region UserInRole
	public partial class UserInRole : BaseEntity
	{
		/// <summary>
		/// Get or set UserId
		/// </summary>
		public Int32 UserId { get; set; }

		/// <summary>
		/// Get or set RoleId
		/// </summary>
		public Int32 RoleId { get; set; }

		/// <summary>
		/// Get or set User
		/// </summary>
		public User User { get; set; }

		/// <summary>
		/// Get or set Role
		/// </summary>
		public Role Role { get; set; }

		public UserInRole()
		{
		}
	}

	public partial class UserInRoleRepository : BaseRepository
	{
	}
	#endregion

	#region Role
	public partial class Role : BaseEntity
	{
		/// <summary>
		/// Get or set Id
		/// </summary>
		public Int32 Id { get; set; }

		/// <summary>
		/// Get or set Name
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// Get or set Users
		/// </summary>
		public List<User> Users { get; set; }

		/// <summary>
		/// Get or set Rights
		/// </summary>
		public List<Role> Rights { get; set; }

		public Role()
		{
			Users = new List<User>();
			Rights = new List<Role>();
		}
	}

	public partial class RoleRepository : BaseRepository
	{
	}
	#endregion

	#region Right
	public partial class Right : BaseEntity
	{
		/// <summary>
		/// Get or set RoleId
		/// </summary>
		public Int32 RoleId { get; set; }

		/// <summary>
		/// Get or set FunctionId
		/// </summary>
		public Int32 FunctionId { get; set; }

		/// <summary>
		/// Get or set IsEnabled
		/// </summary>
		public Boolean IsEnabled { get; set; }

		/// <summary>
		/// Get or set Function
		/// </summary>
		public Function Function { get; set; }

		/// <summary>
		/// Get or set Role
		/// </summary>
		public Role Role { get; set; }

		public Right()
		{
		}
	}

	public partial class RightRepository : BaseRepository
	{
	}
	#endregion

	#region Tab
	public partial class Tab : BaseEntity
	{
		/// <summary>
		/// Get or set Cod
		/// </summary>
		public String Cod { get; set; }

		/// <summary>
		/// Get or set Description
		/// </summary>
		public String Description { get; set; }

		/// <summary>
		/// Get or set Rows
		/// </summary>
		public List<Tab> Rows { get; set; }

		public Tab()
		{
			Rows = new List<Tab>();
		}
	}

	public partial class TabRepository : BaseRepository
	{
	}
	#endregion

	#region TabRow
	public partial class TabRow : BaseEntity
	{
		/// <summary>
		/// Get or set CodTab
		/// </summary>
		public String CodTab { get; set; }

		/// <summary>
		/// Get or set Cod
		/// </summary>
		public String Cod { get; set; }

		/// <summary>
		/// Get or set Description
		/// </summary>
		public String Description { get; set; }

		/// <summary>
		/// Get or set Tab
		/// </summary>
		public Tab Tab { get; set; }

		public TabRow()
		{
		}
	}

	public partial class TabRowRepository : BaseRepository
	{
	}
	#endregion

	#region Function
	public partial class Function : BaseEntity
	{
		/// <summary>
		/// Get or set Id
		/// </summary>
		public Int32 Id { get; set; }

		/// <summary>
		/// Get or set Name
		/// </summary>
		public String Name { get; set; }

		public Function()
		{
		}
	}

	public partial class FunctionRepository : BaseRepository
	{
	}
	#endregion
}
